### ISSUE TITLE
Prefixed methods and functions do not replace the plugin_name_ prefix

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#14]
The process at https://www.generateplugins.com/#generate-plugin does not replace prefixes such as `plugin_name_uninstall` to `my_plugin_name_uninstall`, throughout the entire plugin.

**Comment by TukuToi** [comment]
This is resolved in https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f

**Comment by smileBeda** [comment]
Tested and resolved in #20
