### ISSUE TITLE
Generate plugins does not replace tested up to and required tags in readme/main plugin file

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#15]
Generating a plugin does not replace the `Requires at least: 1.0.0` and `Tested up to: 5.8` parts in the main file or readme.

**Comment by TukuToi** [comment]
This is resolved in https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f

**Comment by smileBeda** [comment]
Tested and resolved in #20
