### ISSUE TITLE
Warnings logged when bulk activating/deactivating new plugin

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#16]
These warnings happen only when using bulk activate/deactivate mode. They are due to a missing check for isset() in the activate and deactivate classes, possibly also in the uninstall process.

**Comment by TukuToi** [comment]
This is resolved in lats commit to BPBP and also https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f

**Comment by smileBeda** [comment]
Tested and resolved in #20
