### ISSUE TITLE
Sync GIt repo <> Online instance <> BPBP repo 

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#17]
Once the bugs #14, #15, and #16 are solved, make sure to sync all repos with the updated and fixed version.

**Comment by TukuToi** [comment]
This should be done mostly in latest develop https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f

**Comment by smileBeda** [comment]
Tested and resolved in #20
