### ISSUE TITLE
Update version of "Tested up to"

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#18]
`$file_contents = str_replace( 'Tested up to: 5.7', 'Tested up to: ' . $new_data['plugin_tested'], $file_contents );`, `tukutoi-plugin-generator/public/class-tkt-plugin-generator-public.php:314`

This will not replace because the BPBP `Tested up to:` is 5.9...

**Comment by TukuToi** [comment]
This should be fixed in latest develop commit https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f

**Comment by smileBeda** [comment]
Tested and resolved in #20
