### ISSUE TITLE
Add replace for plugin_name_ / change plugin_name_ to pfx_

### ISSUE THREAD

**Issue by TukuToi** [TukuToi/tukutoi-plugin-generator#19]
Currently prefixed stuff with `plugin_name_` does not get replaced.
We have a method to replace things that start with `pfx_`, so just update the source (BPBP) to use `pfx_` instead of `plugin_name_`

**Comment by TukuToi** [comment]
This should be resolved in latest #8 

Testing tomorrow.

**Comment by smileBeda** [comment]
Tested and resolved in #20
